model_list:
  # OpenRouter Models (Primary - using your API key)
  - model_name: gemini-2.5-pro
    litellm_params:
      model: openrouter/google/gemini-2.5-pro
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      extra_headers:
        HTTP-Referer: https://bytebot.ai
        X-Title: ByteBot
  
  - model_name: gemini-2.5-flash
    litellm_params:
      model: openrouter/google/gemini-2.5-flash
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      extra_headers:
        HTTP-Referer: https://bytebot.ai
        X-Title: ByteBot

  - model_name: claude-sonnet-4
    litellm_params:
      model: openrouter/anthropic/claude-3.5-sonnet
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      extra_headers:
        HTTP-Referer: https://bytebot.ai
        X-Title: ByteBot

  - model_name: gpt-4o
    litellm_params:
      model: openrouter/openai/gpt-4o
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      extra_headers:
        HTTP-Referer: https://bytebot.ai
        X-Title: ByteBot

  - model_name: claude-opus-4
    litellm_params:
      model: openrouter/anthropic/claude-3-opus
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      extra_headers:
        HTTP-Referer: https://bytebot.ai
        X-Title: ByteBot

  # Additional OpenRouter Models
  - model_name: openrouter-gemini-2.5-pro
    litellm_params:
      model: openrouter/google/gemini-2.5-pro
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      extra_headers:
        HTTP-Referer: https://bytebot.ai
        X-Title: ByteBot

  - model_name: openrouter-claude-sonnet
    litellm_params:
      model: openrouter/anthropic/claude-3.5-sonnet
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      extra_headers:
        HTTP-Referer: https://bytebot.ai
        X-Title: ByteBot

  - model_name: openrouter-gpt-4o
    litellm_params:
      model: openrouter/openai/gpt-4o
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1
      extra_headers:
        HTTP-Referer: https://bytebot.ai
        X-Title: ByteBot

  # Fallback models (if you have other API keys)
  - model_name: anthropic-claude-opus-4
    litellm_params:
      model: anthropic/claude-opus-4-20250514
      api_key: os.environ/ANTHROPIC_API_KEY
  
  - model_name: anthropic-claude-sonnet-4
    litellm_params:
      model: anthropic/claude-sonnet-4-20250514
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: openai-gpt-4.1
    litellm_params:
      model: openai/gpt-4.1
      api_key: os.environ/OPENAI_API_KEY
  
  - model_name: openai-gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY

  - model_name: google-gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY
  
  - model_name: google-gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY
